# Generated by Django 3.2.8 on 2021-10-25 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('candidate_name', models.CharField(max_length=250)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('user_id', models.UUIDField()),
                ('candidate_id', models.UUIDField()),
                ('vote_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=250)),
            ],
        ),
    ]
